Version: 2.0.0
Type: instance
Metadata:
  name: Project Apollo
  description: A top-secret research project to the moon
Auth:
  userId: process.env.USER_ID
  projectId: process.env.PROJECT_ID
  accessKey: process.env.ACCESS_KEY
  secretKey: process.env.SECRET_KEY
Path:
  schema: ./studio.schema.ts
  docker: ./docker-compose.yml
Environment:
  testing:
    startBlock: 20813569
    network: Arbitrum
    execution: parallel
    rpc: https://eth.llamarpc.com
    range: 2
  deployment:
    startBlock: latest
    network: Arbitrum
    execution: parallel
Resources:
  - name: tokenmessenger
    abi: src/abis/tokenmessenger.json
    type: contract/event
    address: "0x19330d10D9Cc8751218eaf51E8885D058642E08A"
    triggers:
      - event: >-
          DepositForBurn(uint64 indexed,address indexed,uint256,address
          indexed,bytes32,uint32,bytes32,bytes32)
        handler: src/handlers/DepositForBurn.DepositForBurnHandler
  - name: tokenMinter
    abi: src/abis/tokenMinter.json
    type: contract/event
    address: "0xE7Ed1fa7f45D05C508232aa32649D89b73b8bA48"
    triggers:
      - event: SetBurnLimitPerMessage(address indexed,uint256)
        handler: src/handlers/SetBurnLimitPerMessage.SetBurnLimitPerMessageHandler
  - name: messageTransmitter
    abi: src/abis/messageTransmitter.json
    type: contract/event
    address: "0xC30362313FBBA5cf9163F0bb16a0e01f01A896ca"
    triggers:
      - event: MessageReceived(address indexed,uint32,uint64 indexed,bytes32,bytes)
        handler: src/handlers/MessageReceived.MessageReceivedHandler
